GET http://localhost:3010

### Create a new user
POST http://localhost:3010/auth/signup
content-type: application/json

{
    "email" : "admin@admin.com",
    "password" : "12341234"
}

### Login
POST http://localhost:3010/auth/signin
content-type: application/json

{
    "email" : "admin@admin.com",
    "password" : "12341234"
}

### Get the current user information
Get http://localhost:3010/auth/whoami

### Logout
POST http://localhost:3010/auth/signout

### Find a particular user with a given ID
GET http://localhost:3010/auth/6

### Find all users with a given email
GET http://localhost:3010/auth?email=

### Delete a user given id
DELETE http://localhost:3010/auth/6

### Update a user
PATCH http://localhost:3010/auth/1453453
content-type: application/json

{
}